POST http://localhost:8001/member/passenger/save
Content-Type: application/json
Accept: application/json

{
  "memberId": "123",
  "name": "zhangsan",
  "idCard": "123444",
  "type": "1"
}
###
POST http://localhost:8000/member/passenger/save
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "name": "zhangsa4n",
  "idCard": "1234444",
  "type": "1"
}
###
###
GET http://localhost:8000/member/passenger/list?pageNo=1&pageSize=2
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

###
###
PUT http://localhost:8000/member/passenger/save
Content-Type: application/json
Accept: application/json
Authorization: {{token}}

{
  "id": "1728682522352685056",
  "memberId": "1724348987919699968",
  "name": "zhangsan",
  "idCard": "1234444",
  "type": "1"
}

###
