GET http://localhost:8001/member/count
Accept: application/json
###

GET http://localhost:8000/member/count
Accept: application/json

###
POST http://localhost:8001/member/register
Content-Type: application/json
Accept: application/json

{
  "mobile": "1234567890"
}
###
POST http://localhost:8001/member/sendCode
Content-Type: application/json
Accept: application/json

{
  "mobile": "12345678901"
}
###
POST http://localhost:8001/member/login
Content-Type: application/json
Accept: application/json

{
  "mobile": "12345678901",
  "verificationCode": "8888"
}


> {%
client.log(JSON.stringify(response.body));
client.log(JSON.stringify(response.body.data.accessToken));
client.global.set("token", response.body.data.accessToken);
%}
###