server:
  port: 8000
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

      routes:
        - id: member
          uri: http://localhost:8001
#          uri: lb://member
          predicates:
            - Path=/member/**


